name: Java CI with Maven
on:
  push:
    branches: [ main, maven_to_gradle ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: config gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3
      - name: build with gradle
        run: gradle build test